### PR TITLE
Callback function after rendering is completed

### PR DESCRIPTION
**Pull request by plinioasf**
Based on @jeevasusej #208 pull request

### CODE REVIEW

**Comment by dabeng** [comment]
Hi  @plinioasf , thanks a lot for your enthusiastic discussions, you can make use of event init and callback initCompleted since orgchart v1.4.0 :blush:

**Comment by dabeng** [comment]
I append the following code snippets to trigger initCompleted callback and emit init event:

```js
    var mo = new MutationObserver(function (mutations) {
      mo.disconnect();
      initTime:
      for (var i = 0; i < mutations.length; i++) {
        for (var j = 0; j < mutations[i].addedNodes.length; j++) {
          if (mutations[i].addedNodes[j].classList.contains('orgchart')) {
            if (opts.initCompleted && typeof opts.initCompleted === 'function') {
              opts.initCompleted($chart);
              $chartContainer.triggerHandler({ 'type': 'init.orgchart', 'chart': $chart });
              break initTime;
            }
          }
        }
      }
    });
    mo.observe($chartContainer[0], { childList: true });
```

**Comment by dabeng** [comment]
Hope you guys like the above solution.

**Comment by plinioasf** [comment]
Nice! Thanks for the solution =)

**Comment by dabeng** [comment]
Everyone interested in this callback can play around this [Demo](https://codepen.io/dabeng/pen/vZjpaw)

**Pull request closed without merging**
