### PR TITLE
Adjusting the orgchart pan to be based on the document - allows the m…

### PR DESCRIPTION
**Pull request by gabrielmartin**
This small change should help make the pan option a bit more usable. Much like the panning functionality of Google Maps.

### CODE REVIEW

**Comment by dabeng** [comment]
Hi @gabrielmartin , if you want pan the orgchart within the whole window of browser, you just need to make the `div.chart-container` fullscreen.

**Comment by gabrielmartin** [comment]
Hi @dabeng, here's a better explanation of this change... It allows the mouse to still pan the orgchart even while the mouse is outside of the browser window and/or the chart-container element.

Even if the chart-container is made fullscreen the panning functionality would still be restricted to the boundaries of the chart-container element.

Is there a reason for restricting the mouse movement to within the chart-container element?

Please let me know your thoughts.

**Comment by dabeng** [comment]
At that time, I chose to  use `$chart.on('mousemove')` rather than `$(document).on('mousemove')` for the sake of better usability. If using the latter event binding, orgchart will easily disappear in the view of chart container, it's a bad user experience, right ?

**Comment by dabeng** [comment]
I prefer to prevent such things happen at the beginning rather than create new function centerView() as a unnecessary remedy. Does this policy make sense?

**Comment by gabrielmartin** [comment]
Yup, that makes sense to me.

In my case, I have added a few layers of functionality (chart padding, centring function, etc.) which help with the movement being based on the document. I am also working on adding boundary detection so that the chart stays within the view but can still be moved when the mouse is outside of the browser window.

With all that said, I will close this pull request.

**Pull request closed without merging**
